### ISSUE TITLE
Support for factoring out types

### ISSUE THREAD

**Issue by mathstuf** [bluss/either#17]
In the `futures` crate, there exists their own `Either` type currently. The crate commonly creates an `Either` over two pairs. I'd like to add methods which factor out common types from both sides:

```
Either<(T, A), (U, A)> -> (A, Either<T, U>)
Either<(A, T), (A, U)> -> (A, Either<T, U>)
Either<A, A> -> A
```

Would these be suitable here or do you think they're better as standalone functions in `futures`? The last one probably makes the most sense here at least.

**Comment by Ralith** [comment]
I'd like to see these too, with one tweak: for the first, let it be `Either<(T, A), (U, A)> -> (Either<T, U>, A)` so that ordering is consistent.

**Comment by mathstuf** [comment]
I'll try an have a PR up later today.

**Comment by bluss** [comment]
I'll just add that if you need these for futures, they are better as standalone functions in futures. I think it is unlikely futures switch to using this crate.

**Comment by mathstuf** [comment]
> I think it is unlikely futures switch to using this crate.

rust-lang-nursery/futures-rs#799 :)
