### ISSUE TITLE
Provide an iterator adapter to filtermap/partition left or right branches on `I::Item : Either<L,R>`

### ISSUE THREAD

**Issue by Emilgardis** [bluss/either#20]
relevant https://github.com/japaric/svd2rust/pull/182#discussion_r171350641

**Comment by cuviper** [comment]
[`Itertools::partition_map`](https://docs.rs/itertools/0.7.6/itertools/trait.Itertools.html#method.partition_map) will do this.  If your items are already `Either`, just use an identity function.

**Comment by Emilgardis** [comment]
Having this functionality in itertools does seem logical. Thank you for pointing `partition_map`
