### ISSUE TITLE
Implement From<L> and From<R> for Either<L, R>

### ISSUE THREAD

**Issue by futile** [bluss/either#33]
I suggest adding the two impls:

```rust
impl From<L> for Either<L, R>
```
and
```rust
impl From<R> for Either<L, R>
```
(don't know the right syntax by heart)

This enables the following nice use-case:

```rust
fn foo(e: Either<i32, f32>) {
  // use e
}

fn main() {
  foo(32.into());
  foo(42.0.into());
}
```

Instead of explicitly writing out the type each time.

Is there a problem with this/am I missing something? Otherwise I would write up a PR. Thanks!

**Comment by cuviper** [comment]
There's currently no way to specify `L != R`, but I think rust-lang/rfcs#1834 would make it possible.

Then there's the problem that adding a blanket `impl` is a breaking change.  Someone could already have their own `impl From<Foo> for Either<Foo, Bar>` today, where `Foo` and `Bar` are their local types.

**Comment by futile** [comment]
Doesn't look that that rfc will be merged soon or at all, but yeah it looks to be what's required.

However, I didn't notice that I could simply impl this myself, so I might just do that. Thanks for the tip! Maybe a macro in this crate like `impl_from!(Either<i32, f32>);` might be nice? Or maybe that's not really desired, due to being a macro etc.

**Comment by futile** [comment]
On the topic of the breaking change: With specialization, shouldn't this be non-breaking? Since an already existing impl should be strictly more specific than a blanket impl.

**Comment by cuviper** [comment]
Hmm, maybe specialization will allow this, but that's not stable yet: rust-lang/rust#31844

**Comment by futile** [comment]
Maybe those impls could also be hidden behind a non-default feature flag?

**Comment by futile** [comment]
Thanks for the extensive comment! It looks like all 3 of these would be enabled by having a `impl From<L/R> for Either<L, R>`, or is there something I'm missing? Also, do you see a way to make this work with the current compiler? Otherwise this would depend on specialization/the `L != R` PR anyway. Or would be added through a macro, but I don't really like that solution.

**Comment by JP-Ellis** [comment]
What's the status on this feature?  Is there still an issue if `L` and `R` are the same type?

**Comment by bluss** [comment]
From my perspective, this feature will never be possible. L and R being equal is always going to be an issue.

I think we can close it, that's the least frustrating thing we can do, instead of holding it open as if it's a possibility. Thanks
