### ISSUE TITLE
rustc warning: trait objects without an explicit `dyn` are deprecated

### ISSUE THREAD

**Issue by trivikr** [bluss/either#41]
Following warning is shown while using `either`@`1.5.3` is used as a dependency:
```console
warning: trait objects without an explicit `dyn` are deprecated
   --> /home/trivikr/.cargo/registry/src/github.com-1ecc6299db9ec823/either-1.5.3/src/lib.rs:839:32
    |
839 |     fn cause(&self) -> Option<&Error> {
    |                                ^^^^^ help: use `dyn`: `dyn Error`
    |
    = note: #[warn(bare_trait_objects)] on by default
```

The code which needs to be updated:
https://github.com/bluss/either/blob/cd15a341118b5af765450dcb6380c6dee17ed0f2/src/lib.rs#L839-L841

**Comment by bluss** [comment]
It needs to be updated to allow this warning, until we change the min Rust version.

**Comment by cuviper** [comment]
Since that lint is also newer than our minimum Rust, you may need to stack it:

```rust
#[allow(unknown_lints, bare_trait_objects)]
```
