### ISSUE TITLE
Impl Tokio traits for Either?

### ISSUE THREAD

**Issue by Hirrolot** [bluss/either#44]
How about implementing Tokio traits for `Either`? Not there is [a third-party crate](https://crates.io/crates/tokio-either) for it, but it's kinda ecosystem fragmentation, isn't it?

**Comment by cuviper** [comment]
Given the relative size and scope of the crates, and the fact that `tokio` is still evolving pre-1.0 while `either` is already 1.5, I think it would be better for tokio to (optionally) depend on this crate and implement its traits for `Either`.

**Comment by Hirrolot** [comment]
I agree with you, however, https://github.com/tokio-rs/tokio/issues/1685#issuecomment-548665309. Anyway, thanks for the reply.
