### ISSUE TITLE
set serde derive to use serde untagged

### ISSUE THREAD

**Issue by meltinglava** [bluss/either#46]
Think the way serde is derived is a non-intuitive way. As I think most people do not want the left and right tags for the values.

Suggest adding [untagged](https://serde.rs/enum-representations.html#untagged) to the serde derive. However this would be a breaking change. I do not belive many people are using the serde fetaure as its now implemented.

This will allow us to do something like:
```rust
type ComplicatedType  = HashMap<String, Either<Vec<String>, String>>
```
Some json that would be parsed now would be 
```json
{
    "some_key": "hello",
    "some_other_random_key": ["hello","world!"]
}
```

**Comment by bluss** [comment]
Either is just one two-case enum, and if you have a particular use case, you should of course make an enum that works for you.

It is not obvious if tagged or untagged should be the default for a general two-case enum, but I would lean towards tagged.

**Comment by meltinglava** [comment]
Think Either with serde is usefull when working with rapid prototyping. You get so much for free, like Display... That beeing sed, I agree that Either with conflicting types makes it hard, thow I do not see people using either with simular types for (de)serializing.

**Comment by cuviper** [comment]
FWIW, this was also discussed in #22.

**Comment by meltinglava** [comment]
I opened this issue as I thought tagged was a strange default. Do also think that the serde-untagged feature is looking like a good solution.

**Comment by bluss** [comment]
Ok, it will certainly not be a feature for the reasons clarified in #22.

**Comment by meltinglava** [comment]
Closing as I think this is done the right way, reading further throught it once more.
