### ISSUE TITLE
Publicly expose the `either!` macro?

### ISSUE THREAD

**Issue by thomaseizinger** [bluss/either#57]
The macro can be useful outside of this crate if one wants to deal with both variants in the same way but without them having the same type. For example:

```rust
trait Foo {
    type T;

    fn foo(self) -> Bar<Self::T>;
}

struct Bar<T> {
    inner: T,
}

impl<L, R, LT, RT> Foo for Either<L, R>
where
    L: Foo<T = LT>,
    R: Foo<T = RT>,
{
    type T = Either<LT, RT>;

    fn foo(self) -> Bar<Self::T> {
        let either_bar = either!(self, inner => inner.foo().inner);

        Bar { inner: either_bar }
    }
}
```

**Comment by cuviper** [comment]
We would need to change it to use `$crate`, but given that we already export some macros, this seems ok to me.

For public API, we should also consider whether `either!` is really a good name for what this does. That sounds like something that would *construct* an `Either`, but it's really more of a "map" operation -- `map_either!` perhaps?

**Comment by cuviper** [comment]
I guess it is basically the untyped version of [`Either::either`](https://docs.rs/either/1.6.1/either/enum.Either.html#method.either), so maybe the name `either!` is ok.

**Comment by bluss** [comment]
I can't think of a good name off hand. I think we need something different than `either` - because the macro does not give you two choices- either left or right - it's based around mapping Left => Left and Right => Right using the sameish expression.

**Comment by thomaseizinger** [comment]
> I guess it is basically the untyped version of [`Either::either`](https://docs.rs/either/1.6.1/either/enum.Either.html#method.either), so maybe the name `either!` is ok.
> (Whereas [`Either::map`](https://docs.rs/either/1.6.1/either/enum.Either.html#method.map) still returns an `Either`.)

Not quite. The main difference is that `either!` only takes one closure! Whereas the function takes two!

Maybe `for_each` or `for_both` would be appropriate?

On the topic of names: `Either::either` is functionally similar to `futures::select!`.

**Comment by bluss** [comment]
Yes, that sounds good to me
