### ISSUE TITLE
Bring `std::error::Error` implementation up to latest version

### ISSUE THREAD

**Issue by thomaseizinger** [bluss/either#68]
`std::error::Error` has - for a while - now functions like `source` and `backtrace` which are currently not implemented in our `Error` impl.

I am happy to send a PR for this.

**Comment by cuviper** [comment]
Note that `backtrace` still hasn't been stabilized, but `source` is doable with an MSRV bump, as you mentioned in #69.

**Comment by thomaseizinger** [comment]
> Note that `backtrace` still hasn't been stabilized

I noticed that too when I tried to include it 😁
