### ISSUE TITLE
EitherN heads-up

### ISSUE THREAD

**Issue by cramertj** [bluss/either#9]
I'm working on my own crate https://github.com/cramertj/EitherN-rs to allow for `Either` over more than two types (e.g `Either4` with variants `One`, `Two`, `Three`, and `Four`). I wanted to check with @bluss and the other contributors. As my library's functionality will share many implementation details with this one, I wanted to make sure no one here feels like I'm stealing their hard work. Let me know if you have any problems or would prefer I do anything differently. Thanks!

**Comment by bluss** [comment]
Ok. thanks for the head's up and don't worry about it.

**Comment by cramertj** [comment]
Cool. Thanks-- I appreciate it.
